### ISSUE TITLE
Обзор литературы: введение в предметную область [1] (Graph Laplacian Metric)

### ISSUE THREAD

**Issue by IPPK93** [intsystems/CreationOfIntelligentSystems_RiemannianGeometry#1]
Введение в предметную область начинается с ознакомления с [A Plug&Play P300 BCI Using Information Geometry by A. Barachant 2014](https://arxiv.org/abs/1409.0107) и [Grand: Graph neural diffusion by M.M. Bronstein et al. ICML, 2021.](https://arxiv.org/pdf/2106.10934.pdf). Основной задачей является разбор методов, понимание идей реализации и поиск новых статей с данными алгоритмами и написание обзора по ним.

**Comment by valentinafom** [comment]
[A Plug&Play P300 BCI Using Information Geometry](https://arxiv.org/pdf/1409.0107.pdf)

**Решаемая задача:**
Разработка метода классификации для BCI без калибровки

**Методы:**
1. Риманово расстояние между матрицами для сравнения матриц ковариации сигналов EEG.  
2. Геометрическое среднее для оценки средней матрицы ковариации для каждого класса. 
3. Классификация Minimum Distance to Riemannian Mean (MDM) - сравнивается риманово расстояние новой матрицы до средних каждого класса.
4. Построение матриц ковариации для ERP путем конкатенации среднего ERP и отдельного триала (позволяет учесть временную структуру).
5. Геодезическая интерполяция(по кратчайшему пути на римановом многообразии матриц ковариации) между сгенерированными и индивидуальными средними матрицами по мере сессии (по мере сбора данных от конкретного пользователя, алгоритм все больше использует его индивидуальные характеристики для классификации).


**Предобработка данных:** 
фильтрация, дискретизация и сегментация, вычисление матриц ковариации как входных данных для классификатора.
1. Применяется полосовой фильтр между 1-20 Гц для удаления составляющих низких и высоких частот
2. Сигнал дискретизируется до 128 Гц для уменьшения размерности задачи
3. Производится сегментация сигнала на эпохи длительностью 1 сек относительно момента стимуляции
4. Для классификации ERP вычисляются "super trial" путем конкатенации среднего ERP и отдельной попытки.
5. Вычисляются матрицы ковариации эпох/супер-проб с использованием оценки выборочной ковариационной матрицы 
6. Далее матрицы ковариации подаются на вход алгоритмов классификации MDM или адаптивной реализации

**Comment by valentinafom** [comment]
[GRAND: Graph Neural Diffusion](https://arxiv.org/pdf/2106.10934.pdf)

**Решаемая задача**
Предложить новый подход к построению нейронных сетей на графах, основанный на моделировании диффузионных процессов с помощью дифференциальных уравнений.

**Данные для классификации узлов графа:**
- Citation networks: Cora, Citeseer, PubMed - результаты как для фиксированных, так и для 100 случайных разбиений.
- Coauthor graph: CoauthorCS - содержит данные о научных сотрудничествах между авторами.
- Amazon co-purchase graphs: Computer, Photo - содержат товары, которые часто покупают вместе.
- Open Graph Benchmark dataset: ogb-arxiv - большая цитатная сеть

**Методы**
Используется уравнение диффузии на графах, где матрица дифузивности зависит от функции "внимания" (определяет веса и важность связи между узлами). Варианты GRAND получаются благодаря разным схемам его дискретизации:
1. Explicit and implicit discretization schemes
2. Single-step and multi-step schemes
3. The explicit Euler scheme and implicit Euler scheme
4. Multi-step methods (4th order Runge-Kutta)
5. Использование адаптивных схем с переменной длиной шага (Dormand-Prince)
